language: elixir

elixir:
<<<<<<< HEAD
  - 1.2.5

otp_release:
  - 18.3

script: mix test --no-start

sudo: false # to use Travis' container based environment
=======
  - 1.3.2

otp_release:
  - 19.0

script: mix test --no-start

sudo: false
>>>>>>> Minor fixes
